# Generated by Django 2.2.13 on 2020-09-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='scope_radio',
            field=models.SmallIntegerField(default=0, verbose_name='radio'),
        ),
    ]
