# Generated by Django 2.2.13 on 2020-09-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_show_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='slug_name',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
