# Generated by Django 2.2.13 on 2020-09-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_show_slug_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['name'], 'verbose_name': 'show', 'verbose_name_plural': 'shows'},
        ),
        migrations.RemoveField(
            model_name='show',
            name='fantasy_name',
        ),
        migrations.AddField(
            model_name='show',
            name='name',
            field=models.CharField(default=1, error_messages={'unique': 'A user with that show already exists.'}, max_length=210, unique=True, verbose_name='name'),
            preserve_default=False,
        ),
    ]
