# Generated by Django 2.2.13 on 2020-10-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0008_auto_20201004_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='rate',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='rate'),
        ),
    ]
