# Generated by Django 2.2.13 on 2020-10-04 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0004_auto_20201004_0347'),
        ('shows', '0009_auto_20201004_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socials.UserSocialNetwork', verbose_name='Social Network'),
        ),
    ]
