# Generated by Django 2.2.13 on 2020-10-06 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0010_show_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='social',
        ),
    ]
