# Generated by Django 2.2.13 on 2020-06-23 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='key name')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='social network')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='link')),
                ('icon_class_css', models.CharField(blank=True, max_length=255, null=True, verbose_name='icon of css class')),
            ],
            options={
                'verbose_name': 'social network',
                'verbose_name_plural': 'socials networks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('username', models.CharField(max_length=255, verbose_name='username')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socials.SocialNetwork', verbose_name='social network')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
                'ordering': ['order'],
            },
        ),
    ]
