# Generated by Django 2.2.13 on 2020-06-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='slug_name',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
