# Generated by Django 2.2.13 on 2020-06-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0002_socialnetwork_slug_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialnetwork',
            name='slug_name',
        ),
    ]
