# Generated by Django 2.2.13 on 2020-10-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0003_remove_socialnetwork_slug_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='UserSocialNetwork',
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterUniqueTogether(
            name='usersocialnetwork',
            unique_together={('social', 'username')},
        ),
    ]
