# Generated by Django 2.2.13 on 2020-10-08 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0005_usersocialnetwork_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocialnetwork',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='shows.Show', verbose_name='show'),
        ),
    ]
