# Generated by Django 2.2.10 on 2020-04-19 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name'], 'verbose_name': 'provincia', 'verbose_name_plural': 'provincias'},
        ),
    ]
